#!/usr/bin/env bash
# Runs as a postCreateCommand, once at the end of devcontainer creation
set -e

uv venv .venv
# shellcheck source=/dev/null
source .venv/bin/activate

git submodule update

# Vlsir Dev Install
apt-get update
apt install -y protobuf-compiler
cd /workspaces/Vlsir
./scripts/build_python.sh
uv pip install -e /workspaces/Vlsir/VlsirTools
cd /workspaces/bandgaps-workspace
# Hdl21 Dev Install
uv pip install -e /workspaces/Hdl21
code add /workspaces/Hdl21
https://github.com/cascode-labs/viper
# gh repo clone cascode-labs/viper /workspaces/viper

uv pip install -e ../viper
uv pip install -e .[dev]
