#!/usr/bin/env bash
# Runs as a postCreateCommand, once at the end of devcontainer creation
set -e

uv venv .venv
# shellcheck source=/dev/null
source .venv/bin/activate
git config --global --add safe.directory "*"
git submodule init
git submodule update

# Vlsir Dev Install
apt-get update
# apt install -y protobuf-compiler
# apt install 2to3
# apt install python3-lib2to3
# apt install python3-toolz
uv pip install -e ./Vlsir/VlsirDev
cd /workspaces/bandgaps-workspace/Vlsir
./scripts/build_python.sh
uv pip install -e /workspaces/bandgaps-workspace/Vlsir/VlsirTools
cd /workspaces/bandgaps-workspace
# Hdl21 Dev Install
uv pip install -e ./Hdl21
uv pip install -e ./Hdl21/pdks/Sky130
uv pip install -e ./viper
uv pip install -e ./OpenFASOC
uv pip install -e ./bandgaps[dev]
